### ISSUE TITLE
failed to install on windows 8

### ISSUE THREAD

**Issue by LarryEitel** [willfarrell/angular-modernizr#4]
I ran: `bower install angular-modernizr`

```
C:\Users\Larry\__prjs\ourfield>bower install angular-modernizr
bower cloning git://github.com/willfarrell/angular-modernizr.git
bower cached git://github.com/willfarrell/angular-modernizr.git
bower fetching angular-modernizr
bower checking out angular-modernizr#6991ccb01513fea9e2be5f7762fa6866dba03e79
bower copying C:\Users\Larry\AppData\Roaming\bower\cache\angular-modernizr\fd07c49894dda3e66a79ae8141e34d67

C:\Users\Larry\AppData\Roaming\npm\node_modules\bower\node_modules\tmp\lib\tmp.js:260
  throw err;
        ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Package.generateResourceId (C:\Users\Larry\AppData\Roaming\npm\node_modules\bower\lib\core\package.js:857:23)
    at null.<anonymous> (C:\Users\Larry\AppData\Roaming\npm\node_modules\bower\lib\core\package.js:178:10)
    at Request._callback (C:\Users\Larry\AppData\Roaming\npm\node_modules\bower\lib\core\source.js:38:9)
    at Request.self.callback (C:\Users\Larry\AppData\Roaming\npm\node_modules\bower\node_modules\request\main.js:122:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\Larry\AppData\Roaming\npm\node_modules\bower\node_modules\request\main.js:655:16)
    at Request.EventEmitter.emit (events.js:117:20)
```

**Comment by willfarrell** [comment]
This looks like a bower issue, possibly with Windows only (I run a Mac). Make sure you're using the latest version of bower. `bower -v` should be`0.10.0`. A lot has changed since `0.8.x`. Are you able to install other bower packages?

**Comment by LarryEitel** [comment]
I attempted to upgrade bower with `npm install bower -g` and got:

```
npm ERR! peerinvalid The package bower does not satisfy its siblings'
 peerDependencies requirements!
npm ERR! peerinvalid Peer yo@1.0.0-rc.1 wants bower@~0.9.2

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program
 Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bower"
 "-g"
npm ERR! cwd C:\Users\Larry\__prjs\ourfield
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Larry\__prjs\ourfield\npm-debug.log
npm ERR! not ok code 0
```

**Comment by willfarrell** [comment]
Try updating yeoman (yo) to `1.0.0-rc.1.1`, this small update changes the bower dependency from `bower@~0.9.2` to `bower@>=0.9.0` which will support `bower 0.10.0`
